config/routes.rb
GoalAchiever::Application.routes.draw do
  resources :students do
    resources :objectives
  end

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :description, :frequency, :name, :points_required
  belongs_to :student
end

app/models/objective.rb
class Objective < ActiveRecord::Base
  attr_accessible :description, :name, :frequency, :points
  belongs_to :user

  def self.frequencies
  	{
  		"Weekly" =>1,
  		"Twice per Week" => 2,
  		"Three times per Week" => 3,
  		"5 times per Week" => 5,
  		"Daily" => 7
  	}
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :name
  has_many :objectives  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
	
	def create
		@objective = Objective.new(params[:objective])
		@objective.student_id = params[:student_id]
		
		if @objective.save
			render :json => @objective.to_json
		else
			render :nothing => true
		end
		
	end
	

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def index
		@students = Student.all
		
	end

	def show
		@student = Student.find(params[:id])	
	end
	def new
		@student = Student.new
		
	end

	def create
		@student = Student.create(params[:student])
		if @student.save
			flash[:success] = "Student Created"
			redirect_to students_path
		else
			flash[:error] = "Could Not Create Student"
			render :new
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
	%title 
	= stylesheet_link_tag    "application", :media => "all" 
	= javascript_include_tag "application" 
	= csrf_meta_tags 
%body
	= yield

app/views/students/index.html.haml
= link_to "Create Student", new_student_path

%table.table
	%thead
		%th
			student
		%th
	%tbody
		- @students.each do |s|
			%tr
				%td
					= link_to s.name, student_path(s.id)

app/views/students/new.html.haml
%h1 Create New Student
.student-form
	= simple_form_for @student do |f|
		= f.input :name
		= f.button :submit

app/views/students/show.html.haml
%h1 
	= @student.name
.student-objectives
	%h3 Objectives
	%table#student-objectives-table
		%thead
			%tr
				%th
					Objectives
		%tbody
			- @student.objectives.each do |o|
				%tr
					%td 
						= o.name

.objective-form
	%h3 Add Objective
	= simple_form_for [@student, Objective.new],  url: student_objectives_path(@student), remote:true do |f|
		= f.input :name
		= f.input :description
		= f.input :frequency, collection:Objective.frequencies
		= f.input :points
		= f.button :submit